---
# Source: wordpress-stack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wpapp
  labels:
    app: wordpress
    env: dev
    stack: wordpress-stack
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 80      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: LoadBalancer
  selector:
    app: wordpress
    env: dev
    stack: wordpress-stack       # Pod label that service is using to select Pods
