# root tag name
wp:
  name: wpapp
  labels:
    app: wordpress
    env: stage
    stack: wordpress-stack
  image:
    # name of the repository from helm will pull the image
    repository: msalim22/wp
    tag: v2
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    APP_ENV: "stage"
    WORDPRESS_DB_HOST: "wp-database.wpdb.svc.cluster.local"
    WORDPRESS_DB_NAME: "wordpress"
    WORDPRESS_DB_USER: "wordpress"
  secrets:
    WORDPRESS_DB_PASSWORD: d29yZHByZXNz  # Base64 encoded 'wordpress'
  containerPorts:
      http: 80